suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(writexl)
  library(foreach)
  library(doParallel)
})

# This script automates the process of aggregating and analyzing output data 
# from multiple Excel files generated by the "gagga.py" script, which is used 
# for DNA sequence overhang (OH) set analysis. The script collates fidelity 
# scores from these files, applies filtering and scoring techniques, and 
# then uses parallel processing to efficiently generate final OH set cliques 
# based on user-defined parameters. The final results are saved to an Excel 
# file for further analysis by process_gagga.py.

# The overall goal is to streamline the selection and optimization of OH sets 
# by leveraging pre-existing scoring matrices and selecting top-performing 
# sequences based on fidelity data.

# Expected Input Format:
# - **Excel Files**: The script expects multiple Excel files in a specified 
#   directory, each containing the results from the "gagga.py" script. These 
#   files should include raw fidelity scores and associated parameters for 
#   different OH sets.

# The script outputs:
# - A single Excel file containing the aggregated data from all input files.

get_option <- function(arg_name, default) {
  args <- commandArgs(trailingOnly = TRUE)
  match <- grep(paste0("^", arg_name, "="), args)
  if (length(match) > 0) {
    value <- sub(paste0(arg_name, "="), "", args[match])
    if (arg_name == "n_cliques" || arg_name == "top_percent") {
      as.numeric(value)
    } else {
      value
    }
  } else {
    default
  }
}

show_help <- function() {
  cat("
    Usage: Rscript my_script.R [options]

    Options:
      --n_cliques=NUM      Number of cliques in each OH set size to generate 
                           (default: 25)
      --top_percent=NUM    Top percentage of fidelity data to process into 
                           cliques (default: 5)
      --output_file=PATH   Path to save the output file (default: 'all_gagga_data.xlsx')
      --data_directory=DIR Directory for data files (default: '/path/to/data')
      --help               Show this help message and exit
  ")
}

# Function for extracting output data from xlsx files generated by gagga.py
read_data <- function(file) {
  tryCatch({
    data <- read_excel(file, range = "A1:J26", col_names = TRUE) %>% 
      select(raw_fidelity = fidelity, setA = hf_oh_set) %>%  
      mutate(raw_fidelity = str_replace(raw_fidelity, "%", "")) %>% 
      ungroup() %>% 
      mutate(file = file)
    
    params <- read_excel(file, sheet = "Parameters", 
                         range = "A1:V2", col_names = TRUE) %>%
      mutate(file = file) %>% 
      select(file, set_size = SET_SIZE, alpha = ALPHA, 
             beta = BETA, everything()) %>% 
      rename_with(tolower, everything()) 
    
    params_data <- left_join(params, data, by = "file")
    return(params_data)
  }, 
  error = function(e) {
    print(paste("Caught an error:", e$message))
    print("  This is not fatal but indicates a corrupt input file; you can ignore this")
    return(NA)
  })
}

#### MAIN #####

args <- commandArgs(trailingOnly = TRUE)

if ('--help' %in% args) {
  show_help()
  q(status = 0)  # Exit after showing help
}

# Read command line arguments
n_cliques <- get_option("n_cliques", 25)
top_percent <- get_option("top_percent", 5)
data_directory <- get_option("data_directory", "out/gagga")
output_file <- get_option("output_file", "all_gagga_data.xlsx")

# List all gagga output files in results directory
setwd(data_directory)
files <- list.files(pattern = "^gagga_.*\\.xlsx$")

registerDoParallel(detectCores())
print(paste0("Reading input data from ", data_directory, 
             ". This may take a while"))
all_data <- foreach(file = files, .combine = 'rbind', 
                    .packages = "readr") %dopar% {
  suppressWarnings(suppressMessages({
    read_data(file)
  }))
}

all_data <- all_data %>% filter(!is.na(raw_fidelity))

print(paste0("Done reading input data; writing the collated data to ", 
             output_file))
write_xlsx(all_data, output_file)

print(paste0("Rescoring OH set data with multiple scoring matrices; updated ",
             "data will be written to ", output_file))
system("python ../../scripts/rescore.py")

print("Done")
